version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NBA_API_URL=${NBA_API_URL}
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fantasy
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
